export const FETCH_SUBCOMMENTS = "FETCH_SUBCOMMENTS";
export const FETCH_SUBCOMMENTS_SUCCESS = "SUBCOMMENTS_FETCHED_SUCCESS";
export const FETCH_SUBCOMMENTS_FAILED = "SUBCOMMENTS_FETCHED_FAILED";

export const DELETE_SUBCOMMENT = "DELETE_SUBCOMMENT";
export const DELETE_SUBCOMMENT_SUCCESS = "DELETE_SUBCOMMENT_SUCCESS";
export const DELETE_SUBCOMMENT_FAILED = "DELETE_SUBCOMMENT_FAILED";

export const ADD_SUBCOMMENT = "ADD_SUBCOMMENT";
export const ADD_SUBCOMMENT_SUCCESS = "ADD_SUBCOMMENT_SUCCESS";
export const ADD_SUBCOMMENT_FAILED = "ADD_SUBCOMMENT_FAILED";

export const UPDATE_SUBCOMMENT = "UPDATE_SUBCOMMENT";
export const UPDATE_SUBCOMMENT_SUCCESS = "UPDATE_SUBCOMMENT_SUCCESS";
export const UPDATE_SUBCOMMENT_FAILED = "UPDATE_SUBCOMMENT_FAILED";

export const SET_SUBCOMMENTS_COUNT = "SET_SUBCOMMENTS_COUNT";
